### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by vinyll** [sonyarianto/pocketbase-docker#2]
Hey Sony!
I like pocketbase and currently [builing an app based on it](https://github.com/vinyll/tanca).

I was wondering what are the benefits of using Docker or Docker Compose in this use case over the single file execution.

Just being curious about it :)

**Comment by sonyarianto** [comment]
Hi @vinyll thanks for the question. Why Docker? Ya it depends on the requirements. I have all services runs on Docker containers, such as Nginx,  PHP, MySQL, so by dockerized Pocketbase to so I can run many Pocketbase instances for different projects on containers.
